### ISSUE TITLE
Problems with cordova-plugin-local-notifications IOS

### ISSUE THREAD

**Issue by marcelobotega** [ostownsville/cordova-plugin-fcm#29]
Hello, 

Nice work on updating this plugin really appreciate that.

I got a problem with the plugin to work with the local notification plugin (https://github.com/katzer/cordova-plugin-local-notifications) on IOS. Android the plugins work like a charm.

When i use the version v0.9-beta of the local notification, every time a schedule a local notification when the app is in the foreground the method FCMPlugin.onNotification is called.

When i use the latest head version of the local notification plugin the method FCMPlugin.onNotification is never called.

I am really struggling with this problem and cant find a solution.

These too plugins are really incompatible on IOS ? 

These issues seen similar: katzer/cordova-plugin-local-notifications#1311 and katzer/cordova-plugin-local-notifications#1373

If you need some example code i can provide.

Thanks.

**Comment by hechi** [comment]
Hey i also have a problem with the notification app on IOS.
```
$ ionic info                                                                                                                                      <23:46

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 browser 5.0.1 ios 4.5.3
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v8.6.0
    npm               : 5.4.2
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55

Environment Variables:

    ANDROID_HOME : /Users/<user>/Library/Android/sdk

Misc:

    backend : pro
```
Servus

**Comment by chrisjpalmer** [comment]
Hi there.

This problem is likely caused because our plugin hooks into OS methods for getting notifications. Your local notifications are going to trigger this OS method and this onNotification will be called. I think to solve this problem we would have to collaborate with the developers of cordova-plugin-local-notifications and get our plugin to work along side theirs. We essentially need a mechanism to identify when a local notification has caused the OS method to be triggered.

I dont get paid to maintain this plugin and unfortunately I am very busy so I will just tell you upfront I cant do the work. If you would like to however feel most welcome. We will merge your branch if it all works good.

Recently we added some significant fixes for iOS with version 3.0.3. Please check this version out as allows expected functioning of the plugin in even the most recent editions of iOS.

Thanks

**Comment by hechi** [comment]
Hey Chris, thanks for letting us now and also a big thanks for developing :)

**Comment by GunslingerBara** [comment]
Is anyone willing to work with the developers behind the local notification plugin to get them compatible with each other? This has been a long-standing problem for some pretty basic functionality of the OS, would be nice to see it finally resolved :)
